-- scripts/deploy_objects.sql
-- Executed natively inside the Snowflake engine via Git Stage

USE DATABASE CI_CD;
USE SCHEMA DEMO;

CREATE TABLE IF NOT EXISTS CICD_DEPLOYMENT_AUDIT (
    DEPLOYMENT_ID VARCHAR DEFAULT UUID_STRING(),
    DEPLOYED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    TRIGGERED_BY VARCHAR DEFAULT CURRENT_USER(),
    STATUS VARCHAR DEFAULT 'SUCCESS_VIA_ACTIONS_GIT_STAGE'
);

INSERT INTO CICD_DEPLOYMENT_AUDIT (STATUS)
VALUES ('SUCCESS_VIA_ACTIONS_GIT_STAGE');

SELECT * FROM CICD_DEPLOYMENT_AUDIT;
